coreos/go-systemd

- activation/files.go
- activation/files_test.go
- activation/listeners.go
- activation/listeners_test.go
- activation/packetconns.go
- activation/packetconns_test.go
- dbus/dbus.go
- dbus/dbus_test.go
- dbus/methods.go
- dbus/methods_test.go
- dbus/properties.go
- dbus/set.go
- dbus/set_test.go
- dbus/subscription.go
- dbus/subscription_set.go
- dbus/subscription_set_test.go
- dbus/subscription_test.go
- examples/activation/activation.go
- examples/activation/httpserver/httpserver.go
- examples/activation/listen.go
- examples/activation/udpconn.go
- journal/send.go
- login1/dbus.go
- login1/dbus_test.go
- unit/deserialize.go
- unit/deserialize_test.go
- unit/option.go
- unit/option_test.go
- unit/serialize.go
- unit/serialize_test.go
Build tags are not compatible with block comments. Also adds copyright header
to a few places it was missing.
/cc @bcwaldon
> *: switch to line comments for copyright

- README.md
- machine1/dbus.go
- machine1/dbus_test.go
I am working on a patch for docker to have systemd running within a container
log to journald outside of the container.  In order for this to work, the
docker container needs to be registered within machinectl.  This patch
gives go bindings to machinectl in systemd.
> Make systemd running within a docker container register with machinectl

- unit/option.go
This convenience function is used a lot in [rkt/stage1/init/pod.go](https://github.com/coreos/rkt/blob/master/stage1/init/pod.go) and I'd like to reuse it somewhere else.
> unit: add NewUnitOption convenience function

- unit/serialize.go
- unit/serialize_test.go
66542898b0f082300f28123eccc6bea01b4ec343 introduced consolidation of
UnitOptions into Sections during serialization. This preserved ordering
of individual options within sections, but since a map was used to house
the sections their order was nondeterministic.
This change moves to preserving the first-seen order of the sections, as
well as continuing to preserve the order of units with sections. For
example:
[UnitOption{A, B, b}, UnitOption{C, D, d}, UnitOption{A, Z, z}]
will consistently be written as:
[A]
B=b
Z=z
[C]
D=d
Fixes #93 #94
> unit: stable serialization order

- test
Borrowing from the other common CoreOS test scripts, we now:
- build a self-contained gopath for testing if GOPATH is not set
- run all unit tests
- run actual systemd dbus tests if invoked as root
- run gofmt and go vet across all go source files
> *: expand/enhance test script

- README.md
What was originally just a 3 != 5 turned into a small yak shave. Cleans
up the README a bit to describe all of the functionality that go-systemd
now provides.
> readme: small cleanup

- unit/deserialize.go
- unit/deserialize_test.go
- unit/end_to_end_test.go
Builds on #103.
I added what IMHO is logic to properly reserve line continuation which I expressed in this dicussion: https://github.com/coreos/go-systemd/pull/103#discussion_r39170746
> unit: pass through line continuations (extended)

- sdjournal/journal_test.go
Splitting the C bindings into sdjournal broke the test because
the test uses the native journal api to generate log activity.
> sdjournal: import coreos.com/go-systemd/journal in test

- dbus/dbus.go
This will allow go-systemd users to obtain metadata information like version. etc
```go
bus, _ := dbus.New()
systemdVersion, _ := bus.GetManagerProperty("Version")
```
> Add method to obtain systemd1.manager interface properties

- util/util.go
This adds two utility functions which can be used by processes to determine
their context (slice), and whether they are running from a systemd "system"
service.
This is a port of [code in rkt](https://github.com/coreos/rkt/blob/d23669f63644f63c1c5b61ea3c95f90ee9ab66f9/stage1/init/init.go#L399), with a few improvements (correctly freeing CStrings, broader portability for older systemd versions).
To check for whether we're running from a "system service" we use the approach suggested by Lennart (and described [here](https://github.com/coreos/rkt/issues/911#issuecomment-103853978)):
hence: to detect if something is a system service, the best approach is
to check if it is not a user process. There are two kinds of user
processes: those running in session scopes, and those running of the …
> util: add GetRunningSlice, RunningFromSystemService, CurrentUnitName

- util/util.go
This allows rkt to detect that the problem was that we couldn't open
libsystemd and just warn the user.
For example, NixOS has shared libraries in weird paths and we don't want
to just fail if we can't find it. See
https://github.com/coreos/rkt/issues/1879
> util: add ErrSoNotFound error var

- login1/dbus.go
Adds interface for Inhibit method defined here: http://www.freedesktop.org/wiki/Software/systemd/inhibit/
The inhibit method is only useful if it is possible to subscribe to signals on the logind dbus. That's what the `Subscribe` method is for. It can be used like this:
```go
signal := login1Conn.Subscribe("PrepareForSleep")
sig := <-signal
switch sig.Name {
case "org.freedesktop.login1.Manager.PrepareForSleep":
....
}
```
Let me know if you think `Subcribe` should be done differently.
> Add interface for Inhibit method

- sdjournal/journal.go
```sdjournal.GetData()``` annoyingly returns data back as "KEY=VALUE", i.e. ```GetData("MESSAGE")``` returns the string ```MESSAGE=blah blah blah```.  This PR adds a convenience function, ```GetDataValue()``` that returns only the value.  This makes client-side code much cleaner.
> Add GetDataValue() convenience function

- sdjournal/read.go
Previously, Follow() is pretty slow due to the unnecessary creation of the buffer in each read.
> sdjournal: Reuse buffer to speed up the Follow().

- journal/journal.go
When we fail to log a message to journald due to ENOBUFS or EMSGSIZE, we attempt to pass the message to journald by passing it a descriptor attached to some shared memory.  Since we won't be touching it again, we need to close the descriptor after we send it.
> Close the tempfile when journaling large messages

- sdjournal/journal.go
- util/util.go
This allows not having to link users of the library to libsystemd,
detect at runtime if it exists or not and react accordingly.
Also, refactor dlopen code.
> sdjournal: dlopen libsystemd instead of linking against it

- sdjournal/journal.go
- sdjournal/read.go
Simple wrapper around `sd_journal_seek_head`
> sdjournal: add ability to rewind JournalReader

- dbus/dbus.go
I'm trying to use the go-systemd/dbus package with DBus sockets established over SSH.
This is mostly a straw PR, since we could probably find a better way of exposing this.
> Expose dbus.NewConnection

- sdjournal/journal.go
rkt needs this because there's a race where short-lived non-root
processes make the journal unable to get all their information (i.e. the
SYSTEMD_UNIT). We work around it by using SYSLOG_IDENTIFIER.
> sdjournal: export SYSLOG_IDENTIFIER

- sdjournal/journal.go
- sdjournal/journal_test.go
- sdjournal/read.go
This implements/wraps `int sd_journal_seek_cursor(sd_journal* j, const char * cursor);` which allows us to seek by cursor.
> sdjournal: add support for cursors (get&seek&test)

- sdjournal/journal_test.go
Simple test to exercise main code path and error handling of
`NewJournalFromDir()`.
> sdjournal: add test for NewJournalFromDir()

- sdjournal/journal.go
There is a symbol cache (map from function names to their addresses) so
we don't need to call dlsym everytime we call a function from libsystemd
if it was already called before.
Every time we open a new Journal, we call dlopen(), and every time we
close it, we call dlclose(). Since the map was global and we weren't
clearing it up after closing Journal, we were reusing the addresses from
the previous invocation. This is wrong because libsystemd can end up in
a different address the second time we dlopen() it.
Instead, just don't call dlclose() when we close the Journal so
libsystemd remains in the process address space for the whole life of
it. This means the symbol cache will be shared between different Journal
instances.
According to dlopen(3):
If the same shared object is loaded again …
> sdjournal: don't close libsystemd on Close()

- sdjournal/read.go
This fixes the endless loop issue reported by @alban .
> sdjournal: Break the loop if error happens during Write().

- sdjournal/read.go
Introduced in 33ad232a0a876386f9335dfddb21104d1aa4bf88
Fixes #175
Not noticed in CI because travis isn't testing the sdjournal package as it's
not running systemd.
> sdjournal: fix Writer call

- sdjournal/read.go
This patch fixes two issues in JournalReader.Read():
1. The return value of copy() was ignored and JournalReader.Read() was
returning the wrong amount of bytes copied.
2. JournalReader implements the Reader interface so it must be able to read a
specific amount of bytes. Journald on the other hand only allows us to read
full entries of arbitrary size (without byte granularity). JournalReader
therefore needs to internally buffer entries that don't fit in the read buffer.
Callers should keep calling until 0 and/or an error is returned.
Fixes https://github.com/coreos/go-systemd/issues/172
-----
/cc @yifan-gu
> sdjournal: fix incomplete reads in JournalReader.Read()

- dbus/methods_test.go
- test
Some assumptions do not hold anymore on recent debian-derivatives.
Tests updated to avoid failures in modern dbus/systemd environments.
Fixes #165
> dbus: fix testsuite

- .travis.yml
Rework configuration to run testsuite into containerized
environments. This allows to run all tests on travis.
> travis: run whole testsuite in containers

- sdjournal/journal_test.go
Hard-sleep instead of waiting for a journal event.
This fixes a race due to waiting for any events but enumerating only
matching ones.
Closes #180
> sdjournal: fix a race in GetEntry test

- daemon/sdnotify.go
- daemon/sdnotify_test.go
- test
This patch makes SdNotify return value compliant to the sd_notify()
documentation. See sd_notify(3) man page.
Fixes: https://github.com/coreos/go-systemd/issues/184
> daemon: improve SdNotify errors signaling

- util/util.go
- util/util_cgo.go
- util/util_stub.go
Some projects don't need the CGO functions in the util package;
split out the functions into a separate file so CGO_ENABLED=0
works if those functions are never used.
Fixes #171
> util: conditionally build CGO functions

- dbus/methods_test.go
- dbus/properties.go
Should there also be a usage example on how to create a transient scope unit instead of a transient service unit?
Feel free to use https://github.com/mgit-at/systemd-runas/blob/master/main.go as a example on how to use the call with transient scopes.
> dbus: add PropPids to set initial pids of transient scope units

- activation/listeners.go
If we don't specify `NextProtos` HTTP/2 support will be enable when possible. See https://github.com/golang/go/issues/14374#issuecomment-187939699 and https://github.com/golang/go/commit/b5f0aff49503e31002b33198e06708e263c445a7
> Don't specify NextProtos so that we can take advantage of HTTP/2

- sdjournal/journal.go
https://github.com/systemd/systemd/blob/622a0f628cee51851ad00856f9efddedf0799edb/src/journal/sd-journal.c#L936
Since `asprintf`'s `dst` argument has to be freed
Like it's done here: https://github.com/systemd/systemd/blob/29a753df7682424a0ea505698d548f85c514fad5/src/shared/logs-show.c#L471
> sdjournal: fix memory leak in cursor handling

- sdjournal/journal.go
Since defer creates a closure, it ends up freeing the wrong
pointer in these situations (i.e. not the one that ends up
getting allocated by asprintf during the actual sdjournal
call).
> sdjournal: free correct pointer

- sdjournal/journal_test.go
Just a small testfix :smile: 
Probably you should add the `-race` flag to your build script
since the go builtin command  creates a closure, it uses the same err variable than causes race condition in tests
```
go test ./... -race
==================
WARNING: DATA RACE
Write at 0x00c42007a7e0 by goroutine 6:
github.com/coreos/go-systemd/sdjournal.TestJournalFollow()
/home/amenzhinsky/Development/go/src/github.com/coreos/go-systemd/sdjournal/journal_test.go:73 +0x323
testing.tRunner()
/usr/lib/go/src/testing/testing.go:610 +0xc9
Previous write at 0x00c42007a7e0 by goroutine 7:
github.com/coreos/go-systemd/sdjournal.TestJournalFollow.func1()
/home/amenzhinsky/Development/go/src/github.com/coreos/go-systemd/sdjournal/journal_test.go:62 +0x176
Goroutine 6 (running) created at: …
```
> sdjournal: fix race condition in test

- sdjournal/functions.go
- sdjournal/functions_test.go
- sdjournal/journal.go
libsystemdFunctions is shared between Journal instances that can cause
concurrency issues when multiple objects modify it at the same time
```
fatal error: concurrent map writes
goroutine 10 [running]:
runtime.throw(0x4b9623, 0x15)
/usr/lib/go/src/runtime/panic.go:566 +0x95 fp=0xc420028598 sp=0xc420028578
runtime.mapassign1(0x4a0a80, 0xc420014300, 0xc4200286c8, 0xc4200286c0)
/usr/lib/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc420028680 sp=0xc420028598
github.com/coreos/go-systemd/sdjournal.(*Journal).getFunction(0xc4200fe020, 0x4b863e, 0xf, 0x0, 0x0, 0x0)
````
Code to reproduce the issue:
```go
package main
import (
"github.com/coreos/go-systemd/sdjournal"
"sync"
)
func main() {
wg := sync.WaitGroup{}
wg.Add(10)
for i := 0; i < 10; i++ {
go func() {
j, err := sdjournal.NewJournal()
if err …
```
> sdjournal: fix concurent map access

- examples/activation/httpserver/README.md
Two really minor changes:
* add syntax highlighting for the bash example in the activation readme
* fix a really pedantic quoting issue when setting `GOPATH`
> Syntax highlight activation readme

- dbus/properties.go
`PropType()` sets the Type property
I need to set the service `Type` to test this feature https://github.com/coreos/rkt/pull/2826
See also issue: https://github.com/coreos/rkt/issues/3198
> dbus/properties: service type

- sdjournal/journal.go
- sdjournal/read.go
fix inconsistency in return types for journal functions: `NextSkip`,
`Previous`, `PreviousSkip`. Currently they will return (uint64, error),
however according to `sd-journal.h` it should be (int, error)
Journal.Next returns (int, error)
Journal.Previous returns (uint64, error)
https://github.com/systemd/systemd/blob/master/src/systemd/sd-journal.h#L98
> sdjournal: fix return values type

- dbus/dbus.go
This matches the logic in systemd - connect to the private socket first,
if running as root. Fall back to the standard system DBus otherwise.
Fixes: #207
> dbus: make New() fall back to direct systemd connection

- daemon/watchdog.go
- daemon/watchdog_test.go
Add a function `SdWatchdogEnabled()` who check if service have to report its status
This is inspirated from the behavior of `sd_watchdog_enabled`
> daemon: add watchdog checker

- daemon/sdnotify.go
- daemon/sdnotify_test.go
- daemon/watchdog.go
- daemon/watchdog_test.go
This fixes `SdWatchdogEnabled()` behavior when `$WATCHDOG_PID` is unset,
and introduces a new `unsetEnvironment` boolean flag to `SdWatchdogEnabled()`
and `SdNotify()` to clear releveant env variables, aligning to the behavior of native methods.
> daemon: introduce support for cleaning env variables

- .travis.yml
Travis otherwise seems to think this is a Ruby project, and setting it to a Go project just confuses things, because everything we do is inside Docker containers.
> travis: set language to shell

- dbus/methods_test.go
1. dbus: close DBUS connection at the end of every test
As it's recommended to close every DBUS connection at the end of every test, let's add `conn.Close()` for each test. That will prevent potential bugs hitting an upper limit of connections on `/var/run/dbus/system_bus_socket`.
2. dbus: add more tests for unit properties
Add a common test `TestStartStopTransientUnit` for testing more properties to be used for transient units. The following properties are covered.
* PropType("oneshot")
* PropRemainAfterExit
* PropRequires, PropRequiresOverridable
* PropRequisite, PropRequisiteOverridable
* PropWants
* PropBindsTo
* PropConflicts
> dbus: test: fix bugs and add more tests for unit properties

- Jenkinsfile
- scripts/jenkins/periodic-go-systemd-builder.sh
Instead of configuring the 'Periodic go-systemd builder' Jenkins job in
the Jenkins-UI this commit introduces the job specification via Jenkins
job dsl language.
> test: Specify periodic go-systemd builder job as dsl

- sdjournal/journal.go
- sdjournal/journal_test.go
This fixes a bug in the Wait() method on sdjournal.Journal{}.
The C API expects a duration in microseconds. However the method was passing a nonsense value (timeout's absolute time as thousands of seconds since epoch). This resulted in the value being capped to a maximum of 1.5s.
Looks like the bug was introduced here: https://github.com/coreos/go-systemd/commit/31020344488513bba6094ac4bd728c8d7f768194#diff-985ded8023b21268d0d5cf7f29781d2eR203
Fixes https://github.com/coreos/go-systemd/issues/145
> sdjournal: fix Wait() timeout

- util/util_cgo.go
systemd 234 changed the return value for `sd_pid_get_owner_uid` when
we're running from a unit file to -ENODATA.
Fixes #236
> util: fix runningFromSystemService

- sdjournal/journal.go
- sdjournal/journal_test.go
This fixes TestCursor so it returns an error when the ``cursor``
parameter is not the same as the current position.
From SD_JOURNAL_GET_CURSOR(3):
```
sd_journal_test_cursor() returns positive if the current entry
matches the specified cursor, 0 if it does not match the specified
cursor or a negative errno-style error code on failure.
```
> sdjournal: support testing cursor against current position

- sdjournal/journal.go
As per e.g. https://www.freedesktop.org/software/systemd/man/sd_journal_get_realtime_usec.html:
> Note that these functions will not work before sd_journal_next(3) (or related call) has been called at least once, in order to position the read pointer at a valid entry.
The prior wording of the documentation was ambiguous regarding its usage of "current". This change attempts to clarify that it's "current" in terms of "the state of the read pointer, adjusted by the Next/Previous family of functions" vs. "current" in terms of chronology.
> sdjournal: clarify documentation's notion of "current"

- login1/dbus.go
the close function closes the internal dbus connection, which is otherwise inaccessible. This allows for cleaner shutdown for clients of this library.
> login1: add close function

- dbus/methods.go
- dbus/subscription.go
When dispatching updates to sub-state subscribers, `sendSubStateUpdate`
previously called `GetUnitProperties` with a full, escaped unit path.
`getUnitProperties` expected only an unescaped unit name.
This commit changes `getUnitProperties` to take the full, escaped path,
updates `GetUnitProperties` to escape and expand the unit name to a
path, and adds `GetUnitPathProperties` for callers who already have the
full, escaped unit path.
To quickly see the problem, run this go program:
```
package main
import (
"fmt"
"github.com/coreos/go-systemd/dbus"
)
func main() {
conn, _ := dbus.New()
defer conn.Close()
subUpdateCh := make(chan *dbus.SubStateUpdate)
subErrCh := make(chan error)
conn.SetSubStateSubscriber(subUpdateCh, subErrCh)
for {
select {
case subStateUpdate := <-subUpdateCh: …
```
> dbus: fix subStateSubscriber crash

- dbus/dbus.go
- dbus/dbus_test.go
- dbus/methods.go
- dbus/methods_test.go
- dbus/subscription.go
- dbus/subscription_test.go
This PR adds a `SetPropertiesSubscriber` method which is similar to
`SetSubStateSubscriber` but with two important differences:
* Each update includes all changed properties, not just SubState
* Each set of property values from systemd is reported; no update can be
missed. With `SubStateSubscriber`, transient states can be missed
because `sendSubStateUpdate` calls `GetUnitPathProperties` after receiving
the original signal from systemd; by this point, the unit's state may
have changed again. (This behavior is clearly documented, but for some
use cases it might not be acceptable to miss a state transition.)
> dbus: add SetPropertiesSubscriber method

- dbus/subscription.go
This adds several nil and type checks in the dbus subscription logic,
to ensure it won't panic in case of unexpected events.
> dbus: make SetSubStateSubscriber safer

- login1/dbus.go
- login1/dbus_test.go
This PR adds support for more logind methods, specially for session management.
Closes #238
> login1: add support for session management

- dbus/subscription_test.go
This increases timeouts and adds optimistically-sized buffers to
communication channels, to reduce dbus tests flakiness.
> test: make dbus subscription tests more leniant

- activation/listeners.go
- activation/packetconns.go
This is an adaptation of #215 to ensure tests don't fail and extend
the behaviour to PacketConns(). A bit of test coverage is lost, but
just testing if variable environments are not unset in the simple case
doesn't seem worth adding more code.
Fix #215
> activation: close files after creating listeners

- activation/files.go
- activation/files_test.go
- activation/listeners.go
- activation/listeners_test.go
- activation/packetconns_test.go
- examples/activation/activation.go
- examples/activation/listen.go
- examples/activation/udpconn.go
Since v227, systemd can name each listener. This is useful when you
have different socket units activating the same service: you can't
really know in which order the socket will be provided. Systemd adds
an environment variable named LISTEN_FDNAMES for this purpose.
We encapsulate the name in the File object created from the file
descriptor. Unfortunately, once this is turned into a net.Listener,
there doesn't seem to have a way to fetch this information
back. Therefore, two new functions are provided to be able to easily
get named sockets.
The same could be done to PacketConns in the future.
> activation: add two functions to provide listeners with names

- unit/deserialize.go
- unit/deserialize_test.go
- unit/option.go
- Added missing godoc-style code comments
- Omitted redundant second value from range
> Linter warnings fixed for unit sources

- sdjournal/read.go
> sdjournal: fixed typo in message formatter function name

- sdjournal/journal.go
- sdjournal/read.go
Fixed typo in `ErrNoTestCursor`'s comment and added one for `ErrExpired`.
> sdjournal: add docstrings for public error values

- unit/deserialize.go
It's enough to declare err a bit later.
> unit: avoid unneeded variable shadowing

- sdjournal/read.go
When creating a new JournalReader any errors returned by `r.journal.AddMatch(string)` got ignored. I think we should return any errors.
> sdjournal: propagate AddMatch errors in constructor

- sdjournal/read.go
`entry, err := r.journal.GetEntry()` was shadowing the `err` declaration in the outer scope.
> sdjournal: avoid unneeded variable shadowing

- journal/journal.go
I don't think the first check can harm, the second one was more of a typo and the `err` assignment obviously missing.
> journal: Added missing error handling for write & unlink calls

- dbus/methods.go
As mentioned in #223, this method requires systemd v230 or higher. I've added a comment to the method's documentation to avoid further confusion.
Fixes #223.
> dbus: Added systemd requirement note to ListUnitsByNames

- activation/files_test.go
Simple, straight-forward to review linter warning fixes.
> activation: Fixed linter warnings

- README.md
Included `daemon` and `login1` packages in README and fixed the sort order to match the enumeration of packages at the top of the file.
> README: list all packages and fix ordering

- daemon/sdnotify.go
- Added copyright 2015-2018 CoreOS, Inc.
- Proper godoc package comment
- Got rid of named (but unused) return values
Fixes #83.
> daemon: Clean up copyright headers and documentation

- daemon/sdnotify.go
- daemon/watchdog.go
This provides convenient little helper methods for the common service notifications, while hiding the "protocol" details from the API caller.
- SdNotifyReady to signal readiness
- SdNotifyStopping to signal beginning of shutdown
- SdNotifyReloading to signal configuration reloading
- SdNotifyWatchdog to update the watchdog timestamp
> daemon: add convenience constants for SdNotify

- .travis.yml
- activation/files.go
- activation/listeners.go
- activation/packetconns.go
- examples/activation/listen.go
- examples/activation/udpconn.go
Package `activation` was previously offering an option to leave
environment variables untouched, in order to re-use fd at a future
point.
However, re-using fd is unsafe and results in racing against the GC
due to the way how `os.File` is implemented. Moreover, the Go runtime
does not (nor plan to) provide a safe interface for proper temporary
borrowing of existing fd.
Thus, this removes the `unsetEnv` option from all listeners (forcing
to always unset), and only keeps it where ownership can be transferred
back to the caller.
Ref: https://github.com/coreos/go-systemd/pull/250#issuecomment-369625901
Ref: https://github.com/golang/go/issues/24215
> activation: remove unsafe support for fd re-use

- .travis.yml
- Gopkg.toml
- README.md
- activation/common_test.go
- activation/files_test.go
- activation/listeners_test.go
- activation/packetconns_test.go
- journal/journal_test.go
- scripts/travis/pr-test.sh
- util/util_test.go
This rework how are tests are built and run on Travis, splitting it in multiple phases. Thus, it allows to compile with arbitrary golang toolchains (as offered on Travis) and test against arbitrary systemd versions (as shipped by distributions, via Docker).
It also adds a [dep](https://github.com/golang/dep) manifest to fetch dependencies, but no lockfile nor vendor directory.
> travis: split test compilation and run phases

- journal/journal_test.go
This commit introduces tests exercising sending logic for
empty/small/large messages.
> test/journal: add some send tests

- journal/journal.go
- journal/journal_test.go
the validVarName function tries to test for variables starting with an
underscore but there's a missing set of parentheses.
Fixes #284
> journal: fix validation of key names

- machine1/dbus.go
- machine1/dbus_test.go
Add new DBUS methods exposed already by systemd.
* `ListMachines`: lists all active machines
* `ListImages`: lists all images under `/var/lib/machines`.
* `GetMachineAddresses`, which gets a list of IP addresses of the given machine name.
See also https://github.com/kinvolk/kube-spawn/issues/241#issuecomment-425708704
> machine1: add methods ListMachines, ListImages, GetMachineAddresses

- dbus/methods.go
Cleared up some caveats about what units are returned from systemds
ListUnits-method.
Fixes #289
> docs: Add more detail to Conn.ListUnits-doc

- .travis.yml
- Gopkg.toml
- README.md
- dbus/dbus.go
Something in godbus seems to have broken API, thus breaking builds
including `go get`. This patches fixes those changes. I don't know any
background about this change, so if anyone has information, I'd sure
like to know! Thanks
> dbus: Fix API break from godbus

- .travis.yml
- unit/deserialize.go
Caution: If I'm not mistaken `ContainsAny` wasn't available before Go 1.5. I'm not sure which minimum Go version go-systemd is aiming for, but if it's still <1.5 then you might not want to merge this PR.
That being said, I think it reads nicer.
Edit: I was mistaken, `bytes.ContainsAny` was introduced with the 1.7 release.
> unit: use ContainsAny instead of IndexAny

- journal/journal_test.go
TestJournalSend tries to communicate with the local journald and send some messages there. There are environments where go-systemd is useful but there is no local journald available. In these cases it should still be possible to run the test suite successfully.
> journal: skip sending test if journald is unavailable

- machine1/dbus_test.go
Added timeout/retry logic to async `TerminateMachine` test
Resolves #290
> test/machine1: fix sporadic test failures from TestMachine

- examples/activation/httpserver/README.md
systemd-activate is now systemd-socket-activate
> examples: systemd-activate is now systemd-socket-activate

- dbus/methods.go
- dbus/subscription.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
> docs: fix multiple docstrings

- .travis.yml
- README.md
- journal/journal.go
- journal/journal_test.go
This gets rid of the connection ownership problem by using a non-connected Unix datagram socket and an explicit destination to send each message. It does not impact the public API, but it requires a minimum-go version bump due to https://go-review.googlesource.com/c/go/+/45872 (golang 1.10+).
Fixes https://github.com/coreos/go-systemd/issues/5
Fixes https://github.com/coreos/go-systemd/issues/233
Fixes https://github.com/coreos/go-systemd/issues/275
---
Note: as 1.11 got released, all upstream supported versions of the Go runtime have a fixed version of `WriteMsgUnix` that this PR uses. However, this means that the `journal` package won't work on older/buggy runtimes (<= 1.9).
> journal: use a connection-less socket

- sdjournal/journal.go
This was previously just displaying the numeric errno value, resulting in error messages like:
```failed to seek to cursor "foo\n": 22```
The `syscall.Errno` type provides a handy function for returning the string value of an error, so just use that for more informative messages.
> sdjournal: Provide error messages as strings

- machine1/dbus.go
- machine1/dbus_test.go
- Add CreateMachine Call
CreateMachine() is similar to RegisterMachine(), the difference
is CreateMachine will create a scope unit for the machine, and
RegisterMachine will not.
- Add network support
Add *Network Call for both CreateMachine and RegisterMachine which
allow user choose the network interface the host can be used to
communicate with the guest.
- Refactor Machine tests
Currently, we have four ways to start a machine for now. Machine
tests are refactored to make sure all ways have test covered.
> machine1: Add CreateMachine call and network support

- dbus/methods.go
Hi,
I would like to fetch a bunch of systemd service unit properties (e.g. NRestarts, ActiveState, SubState, etc.) in a single call, similar to what I get by running `systemctl show <service>`.
Currently, `dbus/methods.go` exposes two methods for retrieving unit properties:
```
GetUnitTypeProperties(unit string, unitType string)
|-> return c.getProperties(path, "org.freedesktop.systemd1."+unitType) // unitType = Service
GetUnitProperties(unit string)
|-> return c.getProperties(path, "org.freedesktop.systemd1.Unit")
```
Both of these methods call the `getProperties()` helper method:
```
getProperties(path dbus.ObjectPath, dbusInterface string)
|   ...
|-> err = obj.Call("org.freedesktop.DBus.Properties.GetAll", 0, dbusInterface).Store(&props)
```
`getProperties()` will return a different …
> dbus: Introduce GetAllProperties() for fetching all systemd unit properties

- activation/listeners.go
err can't have changed its value and we would have aborted if it's not nil, above.
> activation: fix tautological error handling

- .gitignore
- .travis.yml
- Gopkg.toml
- README.md
- dbus/dbus.go
- dbus/methods.go
- dbus/methods_test.go
- dbus/properties.go
- dbus/subscription.go
- examples/activation/activation.go
- examples/activation/httpserver/httpserver.go
- examples/activation/listen.go
- examples/activation/udpconn.go
- go.mod
- go.sum
- import1/dbus.go
- login1/dbus.go
- machine1/dbus.go
- machine1/dbus_test.go
- sdjournal/functions.go
- sdjournal/journal_test.go
- util/util_cgo.go
This PR adds a `go.mod` and `go.sum` to the project which contains the latest dependencies. It would be awesome if we could tag a release according to semver after this PR got merged, WDYT? :innocent:
> Add go module support

- unit/deserialize.go
An openshift/machine-config-operator user wrote an invalid unit,
and printing the contents as a byte array is unnecessary; it's
almost certain to be a valid string, we just found a syntax error.
> deserialize: Use quote to print possibly-invalid string

- unit/deserialize.go
- unit/deserialize_test.go
- unit/section.go
- unit/serialize.go
- unit/serialize_test.go
The existing unit.Deserialize() function does not contain all the
semantic data in a unit file. Specifically it does not fully
support multiple duplicate sections. It does correctly parse the sections,
but the `[]*UnitOption` data structure does not tell the caller,
in the case of a unit file with duplicate section names, *which*
section the UnitOptions are from.
This may matter.
For example, a `/etc/systemd/network/*.network` file can have multiple
`[Route]` entries. Just returning an array of `Section, Name, Value`
tuples does not tell the caller which `[Route]` a given `Name, Value`
pair belongs to.
Ex:
```
[Route]
Gateway=10.0.100.1
Destination=10.0.0.1/24
[Route]
Gateway=10.0.100.2
Destination=10.0.2.1/24
```
This unit file will generate the following from `unit.Deserialize()`
``` …
```
> unit: deserialize keeps all semantic data

- unit/deserialize.go
This renames and un-exports two private constants that are public
by mistake (but never part of a release).
> unit: do not export private constants

- README.md
This updates documentation links in README, in order to use the new
module setup and abandon the now deprecated `godoc.org`.
> docs: update docs links in README

- dbus/dbus.go
This patch allows passing context value to dbus connection opening functions.
> dbus: add context to open functions

- dbus/methods.go
This feature allow pass context to dbus methods. 
Useful in cases:
* then we need to cancel execution
* set timeout for execution
I've just forwarded context.Background creation to the dbus methods [from goddbus/dbus Call](https://github.com/godbus/dbus/blob/efee8394fa9a426004eb24eed1dee80f5efd90af/object.go#L34)
> dbus: add context-aware methods

- activation/files_unix.go
- activation/files_windows.go
- journal/journal_unix.go
- journal/journal_windows.go
`activation` doesn't build on Windows because `syscall.CloseOnExec` takes a `syscall.Handle` rather than an `int` there.
https://github.com/coreos/go-systemd/blob/87511f396ae9991f8589f6e6dcf58e28a91ba52b/activation/files.go#L55-L59
This fixes this with a build constraint returning `nil` on Windows, which makes it a NOP and I guess follows the philosophy of most of the project.
> Fix building on windows

- sdjournal/journal.go
- sdjournal/journal_test.go
sd_journal_next is supposed to return 0 (i.e. EOF) if called at the end of the journal, which would make this issue immediately apparent. However, there is an open bug that causes it to advance to the *wrong* message instead (not the last one in the journal) after a call to sd_journal_seek_tail, which causes code which follows the documented use here to produce non-obviously incorrect results (see <https://github.com/systemd/systemd/issues/9934>).
Instead, sd_journal_previous will correctly seek to the last journal entry, with the unavoidable race condition that it may not actually be the last entry if the journal is written to between calls to sd_journal_seek_tail and sd_journal_previous.
This can be verified by comparing the output of `journalctl -o json | tail -1 | jq -r .MESSAGE_ID` …
> sdjournal: SeekTail should be followed by Previous, not Next

- dbus/methods.go
Looks like a refactoring typo made its way into `dbus.GetUnitTypePropertyContext`. Whoops! 
Thank you in advance for the review! 🙇🏽 🙏🏽
> fix typo in GetUnitTypePropertyContext

- .github/workflows/containers.yml
This introduces a small artificial delay after setting up the test
container but before running the tests, in order to let the system
settle.
> ci: let system settle before running tests

- dbus/methods.go
This exposes the ability to send a kill signal to a specific
(sub)process in the unit, rather than all the processes that compose
the unit.
> dbus: add KillUnitWithTarget

- sdjournal/journal.go
podman v3.1.0-rc2 uses v22 go-systemd and fedora rpm builds were failing
for 32-bit arches (i686 and armv7hl).
This commit conditionally defines id128StringMax based on
32-bit v/s 64-bit arches.
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
Closes: https://github.com/coreos/go-systemd/issues/363
/cc @vrothberg @ashcrow @mheon @rhatdan
> sdjournal: fix input argument type in C.Malloc call

- go.mod
- go.sum
Fixes the https://github.com/kubernetes/kubernetes/issues/100328#issuecomment-801741732 needs the patch https://github.com/godbus/dbus/pull/232, now included in v5.0.4.
From v5.0.3 to v5.0.4 mainly some small patches https://github.com/godbus/dbus/compare/v5.0.3...v5.0.4
> gomod: update godbus to v5.0.4

- journal/journal_unix.go
This is done to ensure unix sockets aren't left dangling after each Enabled() call, which
can lead to eventual process resource exhaustion. Fixes #366.
> journal: close unix socket after successful probe

- dbus/dbus.go
- dbus/methods.go
1. Fix `Deprecated:` annocations. They must be at the start of a new
paragraph (IOW it needs an empty line before), otherwise tools
(linters etc.) don't see them. Ref: https://github.com/golang/go/wiki/Deprecated
2. It is weird that the deprecated functions are documented, while
the non-deprecated ones just refer to the deprecated ones.
Move the documentation to non-deprecated functions.
3. Address some nits in docs:
- add missing documentation for some methods;
- add missing punctuation;
- fix bad formatting (in particular, markdown is not supported);
- minor rewording in a few places.
Fixes: 7172a8dbe9f9559 ("dbus: add context-aware methods") PR #340
Fixes: c51f0924bb40cd8 ("dbus: add context to open functions") PR #341
> dbus: fix deprecated marks and docs

- .github/workflows/containers.yml
- .github/workflows/go.yml
Don't bump the minimum Go version, since there are external projects that depend on this package.
> workflows: limit permissions to reading repo contents

- dbus/methods.go
- dbus/methods_test.go
This exposes the functionality of the `GetUnitByPID` method and could be useful in situations where you're trying to find which unit owns a given process.
I chose to convert from `dbus.ObjectPath` to a `string` (the name of the unit) since almost nothing in this library accepts an `dbus.ObjectPath` as an input, and the methods for converting back and forth are private and not available to users. The current output format could then be passed into `ListUnitsByNames` in order to get further information.
> dbus: add support for querying unit by PID

- .github/workflows/go.yml
- activation/files_unix.go
- examples/activation/activation.go
- examples/activation/httpserver/httpserver.go
- examples/activation/listen.go
- examples/activation/udpconn.go
- util/util_cgo.go
- util/util_stub.go
This expands the matrix of Go versions that are being tested with each PR.
In order to support 1.17+, the build constraints had to be updated to make `gofmt` happy.
> ci: add testing using 1.16/1.17/1.18

- login1/dbus.go
Adding those two because I need only them at the moment. The change is super straightforward (Call => CallWithContext).
> login1: add context-aware ListSessions and ListUsers methods

- login1/dbus.go
- login1/dbus_test.go
This PR adds context-aware methods to get a property/all properties for a user or session.
~~I am not sure how to unit-test them, the majority of login1 connection methods have no unit tests. I think it will be possible after #396 (will be possible to mock both dbus.Conn and dbus.BusObject)~~.
> login1: add methods to get session/user properties

- internal/dlopen/dlopen_example.go
- scripts/ci-runner.sh
This adds one missing file that was forgotten during the initial porting. Without that, the test could not even be built.
The internal package is now also properly tested by CI.
Source file is taken verbatim from https://github.com/coreos/pkg/tree/c7d1c02cb6cf99162b9cdbcad2a6a5c10af2ddca/dlopen.
Fixes: https://github.com/coreos/go-systemd/issues/339
> internal/dlopen: fix test and run in CI

- .github/workflows/containers.yml
- examples/journal/main.go
- examples/journal/run.sh
- journal/journal_unix.go
- journal/journal_unix_test.go
- journal/journal_windows.go
- scripts/ci-runner.sh
This function can be used for automatic protocol upgrade described in [1].
Both unit tests and runnable example are included. Only the latter requires systemd, as unit tests are self-sufficient, and only test that JOURNAL_STREAM environment variable is checked properly.
[1] https://systemd.io/JOURNAL_NATIVE_PROTOCOL/#automatic-protocol-upgrading
> journal: add StderrIsJournalStream function

- .github/workflows/containers.yml
- .github/workflows/go.yml
Use non-EOL Linux distro versions, and build test binaries on a sufficiently old GitHub runner image to be compatible with those distros.
Also bump checkout and setup-go actions and add Go 1.20.
> workflows: update Linux distro versions; update actions; add Go 1.20

- internal/dlopen/dlopen.go
- internal/dlopen/dlopen_test.go
The dlerror() value is stored in thread local storage and thus checking the error from go code is not safe because go can schedule goroutines on any other thread at any time. This means it is possible that between the dlsym() or dlclose() call the code get moved to another thread and thus the dlerror() value is not what we expect. Instead because we read now from another thread it will be an error from a different call.
A test is added which without this fix is able to reproduce the problem somewhat reliably.
This issue was observed in the podman CI[1] which uses the sdjournal API.
[1] https://github.com/containers/podman/issues/20569
> dlopen: make error handling thread safe

- .github/workflows/containers.yml
- .github/workflows/go.yml
- internal/dlopen/dlopen_test.go
- scripts/ci-runner.sh
Bump various versions, fix various issues, making CI working again. See individual commits for more details.
One particular thing -- branch protection rules now need to be modified to only require `all-done` jobs (see the last commit).
> Modernize and fix CI

- dbus/methods.go
- dbus/methods_test.go
- fixtures/attach-processes.service
The functionality is available since systemd v238 (see https://github.com/systemd/systemd/pull/8125/commits/6592b9759cae509b407a3b49603498468bf5d276) but was never exposed to go-systemd.
This is to be used by opencontainers/cgroups packages (see https://github.com/opencontainers/cgroups/pull/26) and eventually runc (see https://github.com/opencontainers/runc/pull/4822).
> dbus: add AttachProcessesToUnit

- .github/workflows/containers.yml
- .github/workflows/go.yml
- fixtures/oneshot.service
- go.mod
- login1/dbus_test.go
- scripts/ci-runner.sh
- sdjournal/journal_test.go
Please see individual commits for details.
High level overview:
- move container setup logic to a script
- make apt-get install less verbose
- install known go version in containers
- go.mod: bump go to 1.23
- TestListJobs: fix flakiness
- login1: fix TestListSessions vs new systemd
- sdjournal: don't use fmt.Printf from tests
- djournal/TestJournalGetCatalog: fix vs new systemd
- add more images (newer ubuntu, debian, fedora)
These are moved to a followup PR:
- Replace interface{} with any
- Use for range for integers
- sdjournal/journal_test.go: use slices.Contains
- login1: remove unused method
- sdjournal,machine1: don't use rand.Seed in test
- Remove io/ioutil usage
> Bump go to 1.23, fix tests, add more images

- README.md
This is an addition to commit 73f6754 ("go.mod: bump go to 1.23").
> README: bump minimal Go version

- daemon/watchdog.go
- import1/dbus.go
- internal/dlopen/dlopen.go
- internal/dlopen/dlopen_example.go
- journal/journal_unix.go
- login1/dbus.go
- machine1/dbus.go
- sdjournal/journal.go
- sdjournal/read.go
- unit/deserialize.go
- util/util.go
- util/util_cgo.go
Please see individual commits for details.
> Misc error reporting improvements

- daemon/sdnotify_linux_test.go
- daemon/sdnotify_other.go
- daemon/sdnotify_unix.go
- go.mod
- go.sum
The synchronized service reload protocol added in systemd version 253 requires that the service provides a `MONOTONIC_USEC` field alongside the `RELOADING=1` notification message for synchronization purposes. The value carried in this field must be the system `CLOCK_MONOTONIC` timestamp at the time the notification message was generated as systemd compares it to other `CLOCK_MONOTONIC` timestamps taken by pid1.
While the Go standard library does utilize `CLOCK_MONOTONIC` in the implementation of package "time", the absolute monotonic timestamps in `time.Time` values are not made available to programmers. Users familiar with idiomatic usage of monotonic timestamps in Go might (incorrectly) try to implement `MONOTONIC_USEC` using process-relative monotonic timestamps, like so:
```go
var …
```
> daemon: add `SdNotifyMonotonicUsec` helper function
