- unit/escape.go
- unit/escape_test.go
UnitNameEscape(string) string
UnitNameUnescape(string) string
UnitNamePathEscape(string) string
UnitNamePathUnescape(string) string
*Escape are analogous to `systemd-escape`
*Unescape are analogous to `systemd-escape --unescape`
*Path* flavor is analogous to `systemd-escape --path [--unescape]`
> unit: add systemd-escape unit name escaping/unescaping

- activation/files.go
- activation/listeners.go
- activation/packetconns.go
Use for range, and use the knowledge the everything is zeroed on
allocation, so gaps will be nil in the slice.
> activation: allocate slice if we know the size

- util/util.go
> util: add IsRunningSystemd (similar to sd_booted)

- dbus/dbus.go
Systemd exposes a dbus-like interface at /run/systemd/private which is
just dbus without the auth/hello.
Using this connection Go programs may be written which utilize systemd's
dbus integration without requiring a dbus daemon.
> dbus: add NewSystemdConnection() for connecting directly to systemd.

- dbus/dbus.go
Just the Hello needs to be omitted for direct to systemd connections,
oops!
> dbus: add Auth step to NewSystemdConnection()

- dbus/dbus.go
- login1/dbus.go
- machine1/dbus.go
Includes fix from #99 and also fixes login1 and machine1.
> Fix dbus api

- journal/journal.go
- journal/journal_test.go
- journal/read.go
- journal/send.go
- test
Work in progress. Based on Dan Mace's initial prototype announced here:
http://lists.freedesktop.org/archives/systemd-devel/2014-June/019840.html
Throwing up to start some discussion...
> [RFC] add journal bindings around sd-journal

- activation/listeners.go
/cc @jonboulle @vcaputo 
Relates to https://github.com/docker/docker/pull/17211
> Added possibility to use TLS with systemd socket activation

- sdjournal/journal.go
See http://www.freedesktop.org/software/systemd/man/sd_journal_add_match.html for more information.
> Implement AddDisjunction, AddConjunction and FlushMatches

- sdjournal/journal.go
- sdjournal/read.go
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
> sdjournal: expose sd_journal_set_data_threshold

- sdjournal/journal.go
- util/util.go
Following up #128 with some style clean-up and fixed commit messages.
> *: add util.GetMachineID+journal.NewJournalFromDir

- dbus/methods.go
> add ListUnitFiles method

- sdjournal/journal.go
> sdjournal: Added missing strings package.

- sdjournal/read.go
> sdjournal: Add 'Path' in config to let NewJournalReader() select journal dir.

- examples/activation/activation.go
- examples/activation/httpserver/httpserver.go
- examples/activation/listen.go
- examples/activation/udpconn.go
This means that go get github.com/coreos/go-systemd/... can succeed.
> Add // +build ignore to examples

- dbus/methods.go
- dbus/methods_test.go
- test
…d support)
is a part of this change: https://github.com/endocode/systemd/commit/5b4452a643d924015ed25972d071ad8802aad29c
and this pull request: https://github.com/coreos/fleet/pull/1564
> dbus: add support for new ListUnits* methods

- sdjournal/journal_test.go
Test for the whole `JournalReader.Read()`, and in particular for incorrect read length.
Ref #172
Ref #173
> sdjournal: add test for incorrect Read() length

- sdjournal/read.go
When a JournalReader is initialized with a NumFromTail bigger than
the number of available entries, cursor will be positioned on the
first entry. Upon initial (mandatory) Next invocation, it will
incorrectly start reading from the second entry.
This fixes a pathological case where the first entry of a journal
is always ignored when using NumFromTail.
> sdjournal: fix an implicit seek to head

- sdjournal/journal.go
- sdjournal/journal_test.go
This allows to avoid extra `string` → `[]byte` conversion overhead for cases
when journal field value is e.g. parsed (which usually requires `[]byte`).
> sdjournal: add GetDataBytes() and GetDataValueBytes() to Journal

- dbus/methods.go
- dbus/methods_test.go
- fixtures/mask-unmask.service
add methods to trigger the masking and unmasking of unit files
> dbus: add mask/unmask for unit files

- util/util_stub.go
> util: fix import path

- sdjournal/journal.go
- sdjournal/journal_test.go
add functionality to get all unique values for a given field, equivalent of 
`journalctl -F <field_name>`.
https://www.freedesktop.org/software/systemd/man/sd_journal_query_unique.html
> sdjournal: add GetUniqueValues

- dbus/methods_test.go
- fixtures/reload.service
- fixtures/start-failed.service
Add additional unit tests for the following DBUS methods.
* RestartUnit
* TryRestartUnit
* ReloadUnit
* ReloadOrRestartUnit
* ReloadOrTryRestartUnit
* KillUnit
* ResetFailedUnit
* Reload
> dbus: add additional tests for dbus methods

- daemon/sdnotify.go
- test
Also add a copyright header to code forked from docker project some
years ago
> test: add license header check

- util/util_test.go
add tests for the util module
Fixes #193
Not sure if all the assertions are correct on the return values, but it does add a bit of coverage.
> util: add tests for util package

- .travis.yml
- machine1/dbus.go
- machine1/dbus_test.go
- test
This is a rebase and tweak of #214
> machined: add functions + tests

- sdjournal/journal.go
- sdjournal/journal_test.go
Just [one](https://www.freedesktop.org/software/systemd/man/sd_journal_get_catalog.html) of the C API methods missing but needed.
> sdjournal: add GetCatalog

- machine1/dbus_test.go
This commit introduces a random suffix in machined tests, to make sure
that there are no conflicts between parallel testsuite runs.
> machine1: use random labels in tests

- sdjournal/read.go
> sdjournal: fix goroutine leak

- sdjournal/journal.go
Needed sd_journal_open_files. So added it.
> sdjournal: add NewJournalFromFiles

- dbus/subscription_test.go
Add a test for the fix in
https://github.com/coreos/go-systemd/commit/e1db11dbbff25725abb85feff85529b76787d038
> test: add test for dbus substate subscriptions

- dbus/methods.go
- dbus/methods_test.go
Equivalent to `systemctl is-system-running`.
> dbus: add SystemState method for getting system state

- sdjournal/read.go
this allows users of JournalReader to provide a callback function
that will format the output of each entry.
Fixes #253
> sdjournal: add formating feature to JournalReader

- sdjournal/journal.go
> sdjournal: typo fix

- dbus/methods_test.go
- dbus/set.go
- dbus/subscription.go
Just simple, straight-forward linter warning fixes, which are easy to review.
> dbus: Fixed linter warnings

- sdjournal/journal_test.go
Fixes #257. I opted for not sending `nil` values on success, simply because it would have made the code more convulted & harder to read (and there's no real need for it).
> sdjournal: Fixed concurrency & shadowing issues in tests

- sdjournal/read.go
JournalReader.Follow needs to wait for r.Journal.Wait to return, otherwise
we're opening the door for several race conditions. The JournalReader could
either be re-used or closed while Wait is still running, which seems to
result in undefined behavior. Commonly Wait will return a non-existing,
negative status code in such cases.
Since Wait might return after we stopped reading from waitCh, it's now a
buffered channel of size 1, so it'll never dead-lock in such situations.
Read errors are now correctly propagated to the caller, since err isn't
shadowing the named return value any longer.
We also abort when receiving unknown status codes from Wait now, to prevent
infinitely looping over it.
> sdjournal: Fixed race conditions in JournalReader.Follow

- activation/common_test.go
> tests/activation: fix local test run

- Gopkg.toml
- internal/dlopen/dlopen.go
- internal/dlopen/dlopen_test.go
- scripts/jenkins/periodic-go-systemd-builder.sh
- sdjournal/functions.go
- test
- util/util_cgo.go
The first step for go modules as discussed here: https://github.com/coreos/go-systemd/pull/307#issuecomment-548800039
cc @lucab 
Afterwards I would need assistance in releasing v21 :innocent:
> sdjournal: use internal dlopen package

- examples/activation/activation.go
- examples/activation/httpserver/httpserver.go
- examples/activation/listen.go
- examples/activation/udpconn.go
- go.mod
- machine1/dbus.go
- machine1/dbus_test.go
- sdjournal/functions.go
- sdjournal/journal_test.go
- util/util_cgo.go
Here comes the new version which can be released afterwards I guess.
@lucab PTAL
Refers to #307
> Bump version to v22

- login1/dbus.go
I've created method to get active session, and two other methods to get user and display for specific session.
> login1: support getting active session and session details

- dbus/methods.go
- dbus/methods_test.go
- fixtures/oneshot.service
this adds method `org.freedesktop.systemd1.Manager.ListJobs`
returns all the jobs that are currently queued to be run
> dbus: add ListJobs method

- dbus/dbus.go
- import1/dbus.go
- login1/dbus.go
- machine1/dbus.go
xref https://github.com/kubernetes/kubernetes/issues/100328#issuecomment-1014204604
Pass the Dbus Connected method
> dbus: add Connected methods to check connections status

- journal/journal_unix.go
some application could log to journald conditionally, the implicit
initialization will always create a socket on init.
The Enabled method can be used to initialize the logger and many
applications already use it.
> journal: remove implicit initialization
